"""
problem two of project euler:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
04.1.2021 - mm/dd/yyyy
"""
MILIONS_4 = 4000000

v1 = 1
v2 = 1

total = 0
i = 0
while v1 < MILIONS_4:
  result = v1 + v2
  if result % 2 == 0:
    total += result
  v1 = v2
  v2 = result
  
print(total)